// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJl7kvK3QbHcYzvyAxJ73QBCzGHDcdW0',
    appId: '1:441545837283:web:386ef9280ad0a56d80d3d6',
    messagingSenderId: '441545837283',
    projectId: 'app-fonoaudiologia-gamificado',
    authDomain: 'app-fonoaudiologia-gamificado.firebaseapp.com',
    storageBucket: 'app-fonoaudiologia-gamificado.firebasestorage.app',
    measurementId: 'G-2EKKTX2JKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3XZsKKtQVEbY7Lp-wj5MSD4VR2H3cwLE',
    appId: '1:441545837283:android:c38c8d7df6d95e5380d3d6',
    messagingSenderId: '441545837283',
    projectId: 'app-fonoaudiologia-gamificado',
    storageBucket: 'app-fonoaudiologia-gamificado.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbalf2jQogVZCgYh031iA1ANXvNhxzsqE',
    appId: '1:441545837283:ios:1f5b75fd45655c0f80d3d6',
    messagingSenderId: '441545837283',
    projectId: 'app-fonoaudiologia-gamificado',
    storageBucket: 'app-fonoaudiologia-gamificado.firebasestorage.app',
    iosBundleId: 'com.example.tccSoftwareParaApoioEmExerciciosDeFalaComAnaliseDeDesempenho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbalf2jQogVZCgYh031iA1ANXvNhxzsqE',
    appId: '1:441545837283:ios:1f5b75fd45655c0f80d3d6',
    messagingSenderId: '441545837283',
    projectId: 'app-fonoaudiologia-gamificado',
    storageBucket: 'app-fonoaudiologia-gamificado.firebasestorage.app',
    iosBundleId: 'com.example.tccSoftwareParaApoioEmExerciciosDeFalaComAnaliseDeDesempenho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyJl7kvK3QbHcYzvyAxJ73QBCzGHDcdW0',
    appId: '1:441545837283:web:ca9a17cf69c318c980d3d6',
    messagingSenderId: '441545837283',
    projectId: 'app-fonoaudiologia-gamificado',
    authDomain: 'app-fonoaudiologia-gamificado.firebaseapp.com',
    storageBucket: 'app-fonoaudiologia-gamificado.firebasestorage.app',
    measurementId: 'G-BD3KPLKHQ6',
  );
}
